// <auto-generated />
using APIProyecto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIProyecto.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231023013333_TablaProducto")]
    partial class TablaProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIProyecto.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSeguridad")
                        .HasColumnType("int");

                    b.Property<int>("NumeroTarjeta")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Apellido = "APELLIDO CLEINTE 1",
                            Cedula = "1711512663",
                            Direccion = "DIRECCION CLIETE",
                            Nombre = "CLIENTE 1",
                            NumeroSeguridad = 153,
                            NumeroTarjeta = 123234345
                        });
                });

            modelBuilder.Entity("APIProyecto.Models.ColorProducto", b =>
                {
                    b.Property<int>("IdColorProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColorProducto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdColorProducto");

                    b.ToTable("sgc_ColorProducto");

                    b.HasData(
                        new
                        {
                            IdColorProducto = 1,
                            Nombre = "Café"
                        });
                });

            modelBuilder.Entity("APIProyecto.Models.Producto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMIn")
                        .HasColumnType("int");

                    b.Property<int>("StockMa")
                        .HasColumnType("int");

                    b.Property<int>("TipoProductoIdTipoProducto")
                        .HasColumnType("int");

                    b.HasKey("IdProduto");

                    b.HasIndex("TipoProductoIdTipoProducto")
                        .IsUnique();

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            IdProduto = 1,
                            Stock = 100,
                            StockMIn = 50,
                            StockMa = 200,
                            TipoProductoIdTipoProducto = 1
                        });
                });

            modelBuilder.Entity("APIProyecto.Models.TallaProducto", b =>
                {
                    b.Property<int>("IdTallaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTallaProducto"));

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTallaProducto");

                    b.ToTable("sgc_TallaProducto");

                    b.HasData(
                        new
                        {
                            IdTallaProducto = 1,
                            Talla = "S"
                        });
                });

            modelBuilder.Entity("APIProyecto.Models.TipoProducto", b =>
                {
                    b.Property<int>("IdTipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProducto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoProducto");

                    b.ToTable("sgc_TipoProducto");

                    b.HasData(
                        new
                        {
                            IdTipoProducto = 1,
                            Nombre = "Pantalones"
                        });
                });

            modelBuilder.Entity("APIProyecto.Models.Producto", b =>
                {
                    b.HasOne("APIProyecto.Models.TipoProducto", null)
                        .WithOne("Producto")
                        .HasForeignKey("APIProyecto.Models.Producto", "TipoProductoIdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIProyecto.Models.TipoProducto", b =>
                {
                    b.Navigation("Producto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
